есть ошибки
./media/userfiles/tests_oZwEOwX.py:1:1: F401 'django.test.TestCase' imported but unused

отправлена информация по почте
